version: '3.8'

services:
  adonis_app:
    container_name: adonis_app
    restart: always
    build:
      context: .
      target: production
    ports:
      - ${PORT}:${PORT}
      - "9229:9229"
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    command: node ace serve --watch
